const constants = {
    SET_IMAGE_SOURCE: 'SET_IMAGE_SOURCE',
    SET_INGREDIENT_LIST: 'SET_INGREDIENT_LIST',
    SET_RECIPE_LIST: 'SET_RECIPE_LIST',
    SET_DISH_DETAIL: 'SET_DISH_DETAIL'
}

export default constants
