const constants = {
    SET_IMAGE_SOURCE: 'SET_IMAGE_SOURCE',
    FRIEND_EXP_LEADERBOARD: 'FRIEND_EXP_LEADERBOARD',
    FRIEND_DISH_LEADERBOARD: 'FRIEND_DISH_LEADERBOARD',
    FRIEND_TROPHY_LEADERBOARD: 'FRIEND_TROPHY_LEADERBOARD',
    GLOBAL_EXP_LEADERBOARD: 'GLOBAL_EXP_LEADERBOARD',
    GLOBAL_DISH_LEADERBOARD: 'GLOBAL_DISH_LEADERBOARD',
    GLOBAL_TROPHY_LEADERBOARD: 'GLOBAL_TROPHY_LEADERBOARD',
}

export default constants
